### ISSUE TITLE
code formattting

### ISSUE THREAD

**Issue by jgauffin** [jonfazzaro/skeleton#1]
I would love to help (by contributing). But the code formatting hurt my eyes :/

Would you mind using the standard naming and formatting guidelines? https://msdn.microsoft.com/en-us/library/ms229042(v=vs.110).aspx

**Comment by jonfazzaro** [comment]
I do care about your eyes, but there are schloads of conventions in those guidelines. 

Please make a PR on something you find particularly hurty, so we can chew it over in concrete terms.

**Comment by jgauffin** [comment]
great :)

A PR have been created. I used ReSharper to do the reformatting. It uses most of the C# guidelines that Microsoft have specified.

#2

**Comment by jonfazzaro** [comment]
@jgauffin Merged! Thanks.
